on:
    push:
        branches:
            - github_stars_feature


jobs:
    Run_Ruff:
        name: Linting
        runs-on: ubuntu-latest

        steps:
            - name: Check out git repo
              uses: actions/checkout@v4
            
            - name: Setup Python
              uses: actions/setup-python@v1
              with:
                python-version: 3.12
            
            - name: Install python dependencies
              run: pip install black flake8

            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                black: true
                flake8: true
              env:
                GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}